# This will show whenever new dependencies are added
name: Inspect dependencies
on:
  - push

jobs:
  check_new_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new dependencies
        uses: hiwelo/new-dependencies-action@1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

